---
default:
  from: "steveej/gentoo-base:latest"
  maintainer: "Stefan Junker <code@stefanjunker.de>"
  volumes_from:
    - portage
  packages:
    default:
      package_prefix: "="
      version_delim: "-"
  
portage:
  volumes:
    - /usr/portage
  volumes_from: []

cinder:
  packages:
    sys-cluster/cinder:
      install: Yes
      version: 2014.1.2*
      use:
        +: [mysql]

glance:
  packages:
    app-admin/glance:
      install: Yes
      version: 2014.1.2*
      use:
        +: [mysql]

horizon:
  packages:
    www-apps/horizon:
      install: Yes
      version: 2014.1.2*

keystone:
  packages:
    sys-auth/keystone:
      install: Yes
      version: 2014.1.2*
      use: 
        +: [mysql]

neutron:
  packages:
    net-misc/openvswitch:
      install: Yes
      version: 2.3*
      use:
        -: [modules]
    sys-cluster/neutron:
      version: 2014.1.2*
      use:
        +: [mysql, metadata, server, openvswitch, l3, linuxbridge, dhcp]

nova:
  use:
    +: [rbd, spice, usbredir, xen]
  packages:
    net-misc/openvswitch:
      install: No
      version: 2.3*
      use:
        -: [modules]
    sys-cluster/nova:
      version: 2014.1.2*
      use:
        +: [mysql]

swift:
  packages:
    sys-cluster/swift:
      install: Yes
      version: 2014.1.9999
      use:
        +: [account, container, object, proxy]
